### ISSUE TITLE
image licensing seems dubious

### ISSUE THREAD

**Issue by aaronbrethorst** [jsramraj/RSFlags#1]
> The flags are retrived from a single sprite image which I got from Google image search. You dont have to include the flag images for each and every country. To make this work, you just have to include a single image, and a UIImage subclass from this project.

**Comment by jsramraj** [comment]
@aaronbrethorst  What do you suggest? Can I just clear the few dubious icons? will that help?

**Comment by jsramraj** [comment]
Alternative images are added.

**Comment by aaronbrethorst** [comment]
A cursory search of Google Images suggests that maybe your sprite was obtained from someone on Deviant Art who didn't clearly license their images, but maybe is giving them away for free? It's not clear. When I said "Dubious licensing" above, I meant please clean up the licensing situation and make it clear where your images are from—above and beyond 'a google image search.' thanks.

**Comment by jsramraj** [comment]
Understood and thanks,
I have updated the readme file with the image source and the license now.
